name: '"Create Tag" Action for GitHub Actions'
description: 'GitHub Action to create a git tag'
author: "ydataai"
branding:
  icon: 'tag'
  color: 'red'
inputs:
  github_token:
    description: 'The GitHub token to use (if not provided GITHUB_TOKEN will be use instead)'
    default: ${{ github.token }}
    required: false
  sha:
    description: 'The sha of the commit to tag'
    required: false
  tag:
    description: 'The tag name'
    required: true
  message:
    description: 'The tag message'
    required: true
outputs:
  ref:
    description: 'The tag reference'
runs:
  using: 'node16'
  main: 'dist/index.js'
